CREATE TABLE users (
  id                            TEXT PRIMARY KEY,
  email                         TEXT UNIQUE NOT NULL,
  username                      TEXT UNIQUE,
  name                          TEXT NOT NULL,
  password_hash                 TEXT NOT NULL,
  role                          TEXT NOT NULL DEFAULT 'Editor',
  created_at                    INTEGER NOT NULL,
  active                        INTEGER NOT NULL DEFAULT 0,
  kdf_iterations                INTEGER NOT NULL DEFAULT 600000,
  public_key                    TEXT NOT NULL DEFAULT '',
  wrapped_dek                   TEXT NOT NULL DEFAULT '',
  wrapped_private_key           TEXT NOT NULL DEFAULT '',
  wrapped_dek_recovery          TEXT,
  wrapped_private_key_recovery  TEXT,
  recovery_mode                 TEXT NOT NULL DEFAULT 'private',
  escrowed_recovery             TEXT
);

CREATE TABLE refresh_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id),
  expires_at INTEGER NOT NULL
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

CREATE TABLE reset_token (
  token_hash TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id),
  expires_at INTEGER NOT NULL
);

CREATE INDEX idx_reset_token_user ON reset_token(user_id);

CREATE TABLE activation_token (
  token_hash TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id),
  expires_at INTEGER NOT NULL
);

CREATE INDEX idx_activation_token_user ON activation_token(user_id);

CREATE TABLE retired_usernames (
  username   TEXT PRIMARY KEY,
  reason     TEXT NOT NULL,
  retired_at INTEGER NOT NULL
);

INSERT INTO retired_usernames (username, reason, retired_at) VALUES
  ('admin', 'reserved', strftime('%s','now') * 1000),
  ('administrator', 'reserved', strftime('%s','now') * 1000),
  ('root', 'reserved', strftime('%s','now') * 1000),
  ('system', 'reserved', strftime('%s','now') * 1000),
  ('support', 'reserved', strftime('%s','now') * 1000),
  ('help', 'reserved', strftime('%s','now') * 1000),
  ('contact', 'reserved', strftime('%s','now') * 1000),
  ('info', 'reserved', strftime('%s','now') * 1000),
  ('abuse', 'reserved', strftime('%s','now') * 1000),
  ('security', 'reserved', strftime('%s','now') * 1000),
  ('postmaster', 'reserved', strftime('%s','now') * 1000),
  ('webmaster', 'reserved', strftime('%s','now') * 1000),
  ('mail', 'reserved', strftime('%s','now') * 1000),
  ('email', 'reserved', strftime('%s','now') * 1000),
  ('noreply', 'reserved', strftime('%s','now') * 1000),
  ('no-reply', 'reserved', strftime('%s','now') * 1000),
  ('memoza', 'reserved', strftime('%s','now') * 1000),
  ('official', 'reserved', strftime('%s','now') * 1000),
  ('staff', 'reserved', strftime('%s','now') * 1000),
  ('team', 'reserved', strftime('%s','now') * 1000),
  ('moderator', 'reserved', strftime('%s','now') * 1000),
  ('mod', 'reserved', strftime('%s','now') * 1000),
  ('api', 'reserved', strftime('%s','now') * 1000),
  ('app', 'reserved', strftime('%s','now') * 1000),
  ('www', 'reserved', strftime('%s','now') * 1000),
  ('web', 'reserved', strftime('%s','now') * 1000),
  ('auth', 'reserved', strftime('%s','now') * 1000),
  ('login', 'reserved', strftime('%s','now') * 1000),
  ('logout', 'reserved', strftime('%s','now') * 1000),
  ('register', 'reserved', strftime('%s','now') * 1000),
  ('signup', 'reserved', strftime('%s','now') * 1000),
  ('signin', 'reserved', strftime('%s','now') * 1000),
  ('account', 'reserved', strftime('%s','now') * 1000),
  ('accounts', 'reserved', strftime('%s','now') * 1000),
  ('user', 'reserved', strftime('%s','now') * 1000),
  ('users', 'reserved', strftime('%s','now') * 1000),
  ('username', 'reserved', strftime('%s','now') * 1000),
  ('profile', 'reserved', strftime('%s','now') * 1000),
  ('settings', 'reserved', strftime('%s','now') * 1000),
  ('password', 'reserved', strftime('%s','now') * 1000),
  ('reset', 'reserved', strftime('%s','now') * 1000),
  ('verify', 'reserved', strftime('%s','now') * 1000),
  ('activate', 'reserved', strftime('%s','now') * 1000),
  ('activation', 'reserved', strftime('%s','now') * 1000),
  ('token', 'reserved', strftime('%s','now') * 1000),
  ('oauth', 'reserved', strftime('%s','now') * 1000),
  ('internal', 'reserved', strftime('%s','now') * 1000),
  ('gateway', 'reserved', strftime('%s','now') * 1000),
  ('health', 'reserved', strftime('%s','now') * 1000),
  ('status', 'reserved', strftime('%s','now') * 1000),
  ('public', 'reserved', strftime('%s','now') * 1000),
  ('private', 'reserved', strftime('%s','now') * 1000),
  ('share', 'reserved', strftime('%s','now') * 1000),
  ('shared', 'reserved', strftime('%s','now') * 1000),
  ('note', 'reserved', strftime('%s','now') * 1000),
  ('notes', 'reserved', strftime('%s','now') * 1000),
  ('page', 'reserved', strftime('%s','now') * 1000),
  ('pages', 'reserved', strftime('%s','now') * 1000),
  ('notebook', 'reserved', strftime('%s','now') * 1000),
  ('tag', 'reserved', strftime('%s','now') * 1000),
  ('tags', 'reserved', strftime('%s','now') * 1000),
  ('trash', 'reserved', strftime('%s','now') * 1000),
  ('archive', 'reserved', strftime('%s','now') * 1000),
  ('search', 'reserved', strftime('%s','now') * 1000),
  ('sync', 'reserved', strftime('%s','now') * 1000),
  ('comment', 'reserved', strftime('%s','now') * 1000),
  ('comments', 'reserved', strftime('%s','now') * 1000),
  ('publish', 'reserved', strftime('%s','now') * 1000),
  ('editor', 'reserved', strftime('%s','now') * 1000),
  ('new', 'reserved', strftime('%s','now') * 1000),
  ('create', 'reserved', strftime('%s','now') * 1000),
  ('delete', 'reserved', strftime('%s','now') * 1000),
  ('edit', 'reserved', strftime('%s','now') * 1000),
  ('home', 'reserved', strftime('%s','now') * 1000),
  ('index', 'reserved', strftime('%s','now') * 1000),
  ('dashboard', 'reserved', strftime('%s','now') * 1000),
  ('about', 'reserved', strftime('%s','now') * 1000),
  ('terms', 'reserved', strftime('%s','now') * 1000),
  ('privacy', 'reserved', strftime('%s','now') * 1000),
  ('legal', 'reserved', strftime('%s','now') * 1000),
  ('policy', 'reserved', strftime('%s','now') * 1000),
  ('pricing', 'reserved', strftime('%s','now') * 1000),
  ('billing', 'reserved', strftime('%s','now') * 1000),
  ('payment', 'reserved', strftime('%s','now') * 1000),
  ('subscribe', 'reserved', strftime('%s','now') * 1000),
  ('subscription', 'reserved', strftime('%s','now') * 1000),
  ('pro', 'reserved', strftime('%s','now') * 1000),
  ('premium', 'reserved', strftime('%s','now') * 1000),
  ('free', 'reserved', strftime('%s','now') * 1000),
  ('trial', 'reserved', strftime('%s','now') * 1000),
  ('blog', 'reserved', strftime('%s','now') * 1000),
  ('docs', 'reserved', strftime('%s','now') * 1000),
  ('documentation', 'reserved', strftime('%s','now') * 1000),
  ('faq', 'reserved', strftime('%s','now') * 1000),
  ('news', 'reserved', strftime('%s','now') * 1000),
  ('download', 'reserved', strftime('%s','now') * 1000),
  ('downloads', 'reserved', strftime('%s','now') * 1000),
  ('static', 'reserved', strftime('%s','now') * 1000),
  ('assets', 'reserved', strftime('%s','now') * 1000),
  ('fonts', 'reserved', strftime('%s','now') * 1000),
  ('images', 'reserved', strftime('%s','now') * 1000),
  ('img', 'reserved', strftime('%s','now') * 1000),
  ('media', 'reserved', strftime('%s','now') * 1000),
  ('css', 'reserved', strftime('%s','now') * 1000),
  ('js', 'reserved', strftime('%s','now') * 1000),
  ('cdn', 'reserved', strftime('%s','now') * 1000),
  ('favicon', 'reserved', strftime('%s','now') * 1000),
  ('robots', 'reserved', strftime('%s','now') * 1000),
  ('sitemap', 'reserved', strftime('%s','now') * 1000),
  ('anonymous', 'reserved', strftime('%s','now') * 1000),
  ('guest', 'reserved', strftime('%s','now') * 1000),
  ('test', 'reserved', strftime('%s','now') * 1000),
  ('demo', 'reserved', strftime('%s','now') * 1000),
  ('example', 'reserved', strftime('%s','now') * 1000),
  ('null', 'reserved', strftime('%s','now') * 1000),
  ('undefined', 'reserved', strftime('%s','now') * 1000),
  ('true', 'reserved', strftime('%s','now') * 1000),
  ('false', 'reserved', strftime('%s','now') * 1000);
